name: Node.js fake-store

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        key: ${{ secrets.PRIVATE_KEY }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: 22
        script: |
          cd ~/home/fake-store
          git pull origin develop
          git status
          yarn
          yarn build