name: Node.js fake-store

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: executing remote ssh commands using ssh key 
      uses: appleboy/ssh-action@master 
      with: 
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }} 
        password: ${{ secrets.PASSWORD }} 
        port: 22
        script: |
          cd ~/home/fake-store
          git pull origin develop
          git status
          yarn
          yarn build